name: Codecov report on push to the "main" branch
on:
  push:
    branches: [ main ]
jobs:
  coverage:
    name: Unit tests and coverage report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version-file: './go.mod'
      - name: Build
        run: make build
      - name: Run tests
        run: make test
      - name: Codecov
        uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4